---
version: '3.1'
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - ${DOCKERDIR}/sonarr/config:/config  
      - /mnt/local/downloads/handbrake/tv:/tv   #root dir
      - /mnt/local/downloads/sabnzbd/sab_complete:/complete #keep this dir so container can see the downloads 
      - /mnt/local/downloads/handbrake/recycle/tv:/recycle   #recycle directory
      - /mnt/media/tvSeriesContinuing:/tvSeriesContinuing
    ports:
      - ${PORTS}
    restart: always
