version: "3.3"
services:
  synapse:
    image: "matrixdotorg/synapse:latest"
    container_name: "matrix-synapse"
    restart: unless-stopped
    networks:
      - matrix_net
    volumes:
      # needs to be chown 991:991 
      - "/mnt/local/docker/chat-services/synapse:/data" #when on main VM
      #- ${PATH}/synapse:/data  #When on remote VM
    #environment:
    #  - PUID=${PUID}
    #  - PGID=${PGID}
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=matrix_net
      - traefik.http.services.matrix-synapse.loadbalancer.server.port=8008
      - traefik.http.routers.matrix-synapse.rule=Host(`matrix.${DOMAIN}`)
      - traefik.http.routers.matrix-synapse.entrypoints=http, https
      - traefik.http.routers.matrix-synapse.tls=true
      # Only allow certain IPs since it is internal 
      - traefik.http.routers.matrix-synapse.middlewares=chat-whitelist@docker

  nginx:
    image: nginx:1.12-alpine
    restart: unless-stopped
    networks:
      - matrix_net
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:thebusbees.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    volumes:
      - /mnt/local/docker/chat-services/matrix/nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf
      - /mnt/local/docker/chat-services/matrix/nginx/www:/var/www/
      
  redis:
    image: "redis:latest"
    restart: "unless-stopped"
    container_name: "matrix-redis"
    networks:
      - matrix_net
    
networks:
  matrix_net:
    external: true 
