version: "3.3"
services:
  element:
    image: vectorim/element-web:latest
    container_name: "matrix-element"
    restart: unless-stopped
    #ports:
    #  - 8080:80 
    networks:
      - matrix_net
    volumes:
      - /mnt/local/docker/chat-services/element/config/config.json:/app/config.json
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=matrix_net
      - traefik.http.routers.matrix-element.rule=Host(`chat.${DOMAIN}`)
      - traefik.http.routers.matrix-element.entrypoints=http, https
      - traefik.http.routers.matrix-element.tls=true
      # Only allow certain IPs since it is internal 
      #- traefik.http.routers.matrix-element.middlewares=chat-whitelist@docker 
networks:
  matrix_net:
    external: true 
