---
version: '3.1'
services:
  headphones:
    image: ghcr.io/linuxserver/headphones
    container_name: headphones
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - ${DOCKERDIR}/headphones/config:/config 
      - /mnt/local/downloads/sabnzbd/sab_complete:/complete
      - /mnt/media/music:/music
    ports:
      - ${PORTS}
    restart: always
