---
version: "2.1"
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDIR}/mylar3/config:/config
      - /mnt/media/comics:/comics
      - ${DOWNLOADS}:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
