version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - LOG_LEVEL=debug
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
      - SMTP_HOST=${SMTP}
      - SMTP_FROM=${FROM_EMAIL}
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASS}
      - ADMIN_TOKEN=${TOKEN}
    networks:
      - www-whitelist
    volumes:
      - /mnt/local/docker/vaultwarden/data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.vaultwarden.rule=Host(`${URL}`)
      - traefik.http.routers.vaultwarden.entrypoints=web, websecure
      - traefik.http.routers.vaultwarden.tls=true
      # Only allow certain IPs since it is internal - this is home IP
      - traefik.http.middlewares.vaultwarden-whitelist.ipwhitelist.sourcerange=${ALLOW_IPS}
      #Ignore the cloudflare IPs and show the IP user is coming from
      - traefik.http.middlewares.vaultwarden-whitelist.ipwhitelist.ipstrategy.excludedips=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - traefik.http.routers.vaultwarden.middlewares=vaultwarden-whitelist@docker
networks:
  www-whitelist:
    external: true   
