---
version: "3"
services:
  plex:
    image: plexinc/pms-docker:latest 
    container_name: plex
    network_mode: host
    environment:
      - PUID=$PUID  
      - PGID=$PGID 
      - TZ=America/Chicago
    volumes:
      - /mnt/local_450GB_HDD/docker/plex/config:/config
      - /mnt/local_450GB_HDD/plexTranscode:/transcode
      - /mnt/media:/media    
      - /mnt/dvr:/dvr
      - /mnt/familyMedia:/familyMedia
    restart: unless-stopped
