---
version: "3"
services:
  plex:
    image: plexinc/pms-docker:latest 
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}  
      - PGID=${PGID} 
      - TZ=America/Chicago
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - /mnt/plex/config:/config
      - /mnt/local/plexTranscode:/transcode
      - /mnt/media:/media    
      - /mnt/dvr:/dvr
      - /mnt/familyMedia:/familyMedia
    restart: always
