---
version: "3"
services:
  plex:
    image: plexinc/pms-docker:latest 
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}  
      - PGID=${PGID} 
      - TZ=America/Chicago
      #- PLEX_CLAIM=claim-abc123 #Must be used if spinning up new server or rebuilding.  Use https://www.plex.tv/claim/ to get a new code.
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - /mnt/local/plex/config:/config
      - /mnt/local/plexTranscode:/transcode
      - /mnt/media:/media
      - /mnt/media2:/media2
      - /mnt/downloads:/downloads #temp folder until processed by handbrake.  Allows immediate access to videos without having to wait for handbrake
      - /mnt/dvr:/dvr
      - /mnt/familyMedia:/familyMedia
    restart: always
