version: "3"
services:
  bookstack:
    image: linuxserver/code-server
    container_name: codeserver
    networks:
      - www-whitelist
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - PASSWORD=${PASS}  
      - SUDO_PASSWORD=${ROOTPASS} #optional 
    #ports:
    #  - 8443:8443
    volumes:
       - /mnt/local/docker/code-server/config:/config
       #Add as many folders as you would like below in order to make them available in the code editor
       #- /mnt/local/docker/${FOLDER1}:/config/docker/${FOLDER1}
       #- /mnt/local/docker/${FOLDER2}:/config/docker/${FOLDER1}
       #- /mnt/local/docker/${FOLDER3}:/config/docker/${FOLDER1}
       #or point to a root folder like below
       - /mnt/local/docker/:/config/docker/
    restart: always
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www-whitelist
      - traefik.http.routers.codeserver.rule=Host(`${URL}`)
      - traefik.http.routers.codeserver.entrypoints=http, https
      - traefik.http.routers.codeserver.tls=true
      # Only allow certain IPs since it is internal - this is home IP
      #- traefik.http.middlewares.codeserver-whitelist.ipwhitelist.sourcerange=${ALLOW_IPS}
      #Ignore the cloudflare IPs and show the IP user is coming from
      #- traefik.http.middlewares.codeserver-whitelist.ipwhitelist.ipstrategy.excludedips=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - traefik.http.routers.codeserver.middlewares=ip-whitelist@docker
      - traefik.http.routers.codeserver.tls.certresolver=staging
networks:
  www-whitelist:
    external: true 
