f2b-docker:
  image: crazymax/fail2ban:latest
  restart: unless-stopped
  network_mode: host
  cap_add:
    - NET_ADMIN
    - NET_RAW
  environment:
    - F2B_LOG_LEVE=DEBUG
    - F2B_DB_PURGE_AGE=365d
    - F2B_MAX_RETRY=2
    - F2B_ACTION=%(action_)s
    - F2B_IPTABLES_CHAIN=DOCKER-USER
    - TZ=America/Chicago
  volumes:
    - $DOCKERDIR/fail2ban/data:/data
    - /etc/localtime:/etc/localtime:ro
    - /var/log:/var/log:ro
