version: '2.1'
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - $DOCKERDIR/flame/config:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
    ports:
      - $FLAME_PORTS #5005:5005 typically
    restart: $RESTART
####################################################
  organizr:
      container_name: organizr
      hostname: organizr
      image: organizr/organizr:latest
      ports:
          - $ORGANIZR_PORTS #pick:80
      volumes:
          - $DOCKERDIR/organizr/config:/config
      environment:
          - PUID=$PUID
          - PGID=$PGID
          - TZ=$TIMEZONE
      restart: $RESTART
