version: '3.1'
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
    volumes:
      - $DOCKERDIR/overseerr/config:/config
    ports:
      - $PORTS
    restart: unless-stopped
