---
version: '3.1'
services:
  handbrakevmovies:
    image: jlesage/handbrake
#    cpus: 3.9
    container_name: handbrake_movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - KEEP_APP_RUNNING=1
      - CLEAN_TMP_DIR=1
      #Movie Preset
      - AUTOMATED_CONVERSION_PRESET=Custom/1080p30Stereo #1080p30 is Fast 1080P 1080p30Stereo is Fast 1080P in Stero and 1080p30v2 is very fast 1080P.  Others are 5.1 Audio.
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0 #1 keeps source, 0 deletes after sucessful conversion
      - AUTOMATED_CONVERSION_FORMAT=mp4
      - AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=90 #seconds to be stable before converting to make sure it is not being copied
      - AUTOMATED_CONVERSION_OUTPUT_DIR=/movies
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
    volumes:
      - $DOCKERDIR/handbrake_movies/config:/config:rw
      - $SHAREDIR:/storage:ro 
      - $SHAREDIR/movies:/movies:rw  
      - $DOWNLOADDIRR/ready_for_handbrake_movies:/watch:rw        
    ports:
      - 5802:5800
    restart: unless-stopped
###################################################################
  handbraketv:
    image: jlesage/handbrake
#    cpus: 3.9
    container_name: handbrake_tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - KEEP_APP_RUNNING=1
      - CLEAN_TMP_DIR=1
      - AUTOMATED_CONVERSION_PRESET=Custom/720p30v2 #720p30 is Fast 720P and 720p30v2 is very fast 720P.  Both are same with aduio.
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0 #1 keeps source, 0 deletes after sucessful conversion
      - AUTOMATED_CONVERSION_FORMAT=mp4
      - AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=90 #seconds to be stable before converting to make sure it is not being copied
      - AUTOMATED_CONVERSION_OUTPUT_DIR=/tv-series
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OVERWRITE_OUTPUT=1 #Overwrite file in destination = 1, Do Not overwrite = 0
    volumes:
      - $DOCKERDIR/handbrake_tv/config:/config:rw
      - $SHAREDIR:/storage:ro 
      - $SHAREDIR/quarantine/USB_TV_Series:/tv-series:rw  
      - $DOWNLOADDIRR/ready_for_handbrake_tv:/watch:rw       
    ports:
      - 5801:5800
    restart: unless-stopped
#################################################################
  headphones:
    image: ghcr.io/linuxserver/headphones
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - $DOCKERDIR/headphones/config:/config
      - $DOWNLOADDIR/sab_complete:/complete
#      - $SHAREDIR/quarantine/sabnzbd_unzip_temp:/complete
      - $SHAREDIR/music:/music
    ports:
      - 8282:8181
    restart: unless-stopped
###########################################################
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - $DOCKERDIR/radarr/config:/config
      - $DOWNLOADDIRR/ready_for_handbrake_movies:/handbrake #root directory
      - $DOWNLOADDIRR/sab_complete:/complete  #keep this dir so docker can see the downloads
      #Delete the following after migration
#      - $SHAREDIR/movies:/movies
#      - $SHAREDIR/movies-anime:/movies-anime
#      - $SHAREDIR/movies-christmas:/movies-christmas
#      - $SHAREDIR/movies-hallmark:/movies-hallmark
#      - $SHAREDIR/movies-horror:/movies-horror
#      - $SHAREDIR/quarantine/sabnzbd_unzip_temp:/complete
#      - $SHAREDIR/quarantine:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
################################################################
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - $DOCKERDIR/sabnzbd/config:/config
      - $DOWNLOADDIR/sab_incomplete:/incomplete
      - $DOWNLOADDIRR/sab_complete:/complete
#      - $DOWNLOADDIR/temp:/temp
      #Delete the following after migration
#      - $DOCKERDIR/sabnzbd/sabnzbd_snatch_temp:/incomplete
#      - $SHAREDIR/quarantine/sabnzbd_unzip_temp:/complete
    ports:
      - 8383:8080
      - 9191:9090
    restart: unless-stopped
###############################################################
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - $DOCKERDIR/sonarr/config:/config
      - $DOWNLOADDIRR/ready_for_handbrake_tv:/handbrake #root dir
      - $DOWNLOADDIRR/sab_complete:/complete  #keep this dir so docker can see the downloads    
#      - $SHAREDIR/tv-series:/tv-series
#      - $SHAREDIR/tv-anime:/tv-anime
#      - $SHAREDIR/quarantine/sabnzbd_unzip_temp:/complete
#      - $SHAREDIR/quarantine/:/downloads
#      - $SHAREDIR/quarantine/sabnzbd_unzip_temp/:/handbrake
    ports:
      - 8989:8989
    restart: unless-stopped
###################################################################
#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.10.0/24
