version: '2'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST:  
      DB_MYSQL_PORT:  
      DB_MYSQL_USER:  
      DB_MYSQL_PASSWORD: 
      DB_MYSQL_NAME: 
    volumes:
      - /config/data:/data
      - /config/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_DATABASE: 
      MYSQL_USER:  
      MYSQL_PASSWORD:  
      DISABLE_IPV6:  
    volumes:
      - /mysql/config:/var/lib/mysql
 
