#docker run --rm -it -v "/Users/mroche/plex-meta-manager:/config:rw" meisnate12/plex-meta-manager
version: '3.1'
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: plex_meta_manager
    environment:
      - TZ=America/Chicago
    volumes:
      - $DOCKERDIR/plex-meta-manager/config
    restart: unless-stopped
