version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: $MYSQLCONTAINERNAME
    volumes:
      - $WEBSITEDIR/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLROOTPASSWORD
      MYSQL_DATABASE: $MYSQLDATABASE
      MYSQL_USER: $MYSQLUSER
      MYSQL_PASSWORD: $MYSQLPASSWORD
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: $WORDPRESSCONTAINERNAME
    volumes:
      - $WEBSITEDIR/wordpress:/var/www/html
    ports:
      - $PORTS
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQLUSER
      WORDPRESS_DB_PASSWORD: $MYSQLPASSWORD
      WORDPRESS_DB_NAME: $MYSQLDATABASE
