---
version: '3.1'
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - ${DOCKERDIR}/radarr/config:/config
      - /mnt/local/downloads/handbrake/movies:/movies   #root directory
      - /mnt/local/downloads/sabnzbd/sab_complete:/complete   #keep this dir so container can see the downloads
      - /mnt/local/downloads/handbrake/recycle/movies:/recycle   #recycle directory
      - /mnt/media/movies:/movies
      - /mnt/media2/movies:/movies2
    ports:
      - ${PORTS}
    restart: always
