version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: $MYSQLCONTAINERNAME
    networks:
      - backend 
    volumes:
      - $WEBSITEDIR/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLROOTPASSWORD
      MYSQL_DATABASE: $MYSQLDATABASE
      MYSQL_USER: $MYSQLUSER
      MYSQL_PASSWORD: $MYSQLPASSWORD
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    networks:
      - www
      - backend
    container_name: $WORDPRESSCONTAINERNAME
    volumes:
      - $WEBSITEDIR/wordpress:/var/www/html
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.davidbusbee.rule=Host(`$WWWURL`,`$URL`)
      - traefik.http.routers.davidbusbee.entrypoints=web, websecure
      - traefik.http.routers.davidbusbee.tls=true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQLUSER
      WORDPRESS_DB_PASSWORD: $MYSQLPASSWORD
      WORDPRESS_DB_NAME: $MYSQLDATABASE
networks:
  www:
    external: true 
  backend:
