version: '3.1'
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    ports:
      - 8016:8181
    volumes:
      - /mnt/local/docker/tautulli/config:/config
    networks:
      - www
    restart: always
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.tautulli.entrypoints=http, https
      - traefik.http.routers.tautulli.rule=Host(`${URL}`)
      - traefik.http.routers.tautulli.tls=true
networks:
  www:
    external: true
