---
version: "3"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: www-bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_URL=${HTTPS_URL} # https://whatever.yourdomain.com
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/local/docker/bookstack/config:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.bookstack.rule=Host(`${URL}`)  # whatever.yourdomain.com
      - traefik.http.routers.bookstack.entrypoints=web, websecure
      - traefik.http.routers.bookstack.tls=true
    networks:
      - www
      - backend
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: www-bookstack_db
    networks:
      - backend 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - TZ=America/Chicago
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack_user
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - /mnt/local/docker/bookstack/bookstackdb:/config
    restart: unless-stopped
networks:
  www:
    external: true 
  backend:
