---
version: "3"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: www-bookstack
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - APP_URL=$HTTPS_URL
      - DB_HOST=bookstack_db
      - DB_USER=bookstack_user
      - DB_PASS=$DB_PASS
      - DB_DATABASE=bookstackapp
    volumes:
      - $PATH/docker/bookstack/config:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.bookstack.rule=Host(`$DOMAIN`)
      - traefik.http.routers.bookstack.entrypoints=web, websecure
      - traefik.http.routers.bookstack.tls=true
    networks:
      - www
      - backend
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: www-bookstack_db
    networks:
      - backend 
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$ROOT_PASS
      - TZ=America/Chicago
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack_user
      - MYSQL_PASSWORD=$DB_PASS
    volumes:
      - $PATH/docker/bookstack/bookstackdb:/config
    restart: unless-stopped
networks:
  www:
    external: true 
  backend:
