# I have different container names and paths for the external and internal facing versions.  That way I can use the same compose file
# and just change the env variables
version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: $CONTAINER
    volumes:
      - /mnt/local/docker/$DIRECTORY/data:/www/assets
    networks:
      - www
    environment:
      - UID=$UID
      - GID=$GID
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.$CONTAINER.entrypoints=web, websecure
      - traefik.http.routers.$CONTAINER.rule=Host(`$URL1`,`$URL2`)
      - traefik.http.routers.$CONTAINER.tls=true
networks:
  www:
    external: true
