#Used for homelab
version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: homer-homelab
    volumes:
      - /mnt/local/docker/homer-homelab/data:/www/assets
    networks:
      - www-whitelist
    environment:
      - UID=${UID}
      - GID=${GID}
    restart: unless-stopped
    ports:
      - 8003:8080
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik   
      - traefik.enable=true
      - traefik.docker.network=www-whitelist
      - traefik.http.routers.secure-homer.entrypoints=http, https
      - traefik.http.routers.secure-homer.rule=Host(`${URL1}`,`${URL2}`)
      - traefik.http.routers.secure-homer.tls=true
      # Only allow certain IPs since it is internal
      #- traefik.http.middlewares.secure-homer-whitelist.ipwhitelist.sourcerange=${ALLOW_IPS}
      #Ignore the cloudflare IPs and show the IP user is coming from
      #- traefik.http.middlewares.secure-homer-whitelist.ipwhitelist.ipstrategy.excludedips=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - traefik.http.routers.secure-homer.middlewares=ip-whitelist@docker
networks:
  www-whitelist:
    external: true
