# I have different container names and paths for the external and internal facing versions.  That way I can use the same compose file
# and just change the env variables
version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: ${CONTAINERNAME}
    volumes:
      - ${DOCKERROOT}/data:/www/assets
    networks:
      - www
    environment:
      - UID=${UID}
      - GID=${GID}
    restart: unless-stopped
    ports:
      - ${PORT}:8080
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.www-homer.entrypoints=http, https
      - traefik.http.routers.www-homer.rule=Host(`${URL1}`,`${URL2}`)
      - traefik.http.routers.www-homer.tls=true
networks:
  www:
    external: true
