version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: $CONTAINER
    volumes:
      - /mnt/local/docker/$DIRECTORY/data:/www/assets
    networks:
      - www 
    environment:
      - UID=$UID
      - GID=$GID
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.$ROUTER.entrypoints=web, websecure
      - traefik.http.routers.$ROUTER.rule=Host(`$WWWDOMAIN`,`$DOMAIN`)
      - traefik.http.routers.$ROUTER.tls=true
networks:
  www:
    external: true
