#will check for unhealthy containers that have the following label:
#deunhealth.restart.on.unhealthy=true
version: "3.7"
services:
  deunhealth:
    image: qmcgaw/deunhealth:latest
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=debug #info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=America/Chicago
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
