version: '3'

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - www
      - homelab
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!

    volumes:
      - $PATH/docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PATH/docker/traefik/logs:/var/log/traefik/
      - $PATH/docker/traefik/certs:/etc/certs
networks:
  www:
    external: true
  homelab:
    external: true
