# This version is for use with NGIX Proxy Manager.  If you use Traefik, use the other file
version: '3.7'

services:
  authelia:
    image: authelia/authelia:4
    container_name: authelia
    volumes:
      - "${DOCKER_PATH}/authelia:/config"
    restart: unless-stopped
#    networks:
#      - www
    ports:
      - ${PORT}:9091
    environment:
      - TZ=${TZ}

#networks:
#  www:
#    external: true 
