version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: ${MYSQLCONTAINERNAME}
    networks:
      - backend 
    volumes:
      - ${WEBSITEDIR}/mysql:/var/lib/mysql
    restart: always
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${PORT}:80
    networks:
      - www
      - backend
    container_name: ${WORDPRESSCONTAINERNAME}
    volumes:
      - ${WEBSITEDIR}/wordpress:/var/www/html
    restart: always
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.$ROUTERNAME.rule=Host(`${URL1}`,`${URL2}`,`${URL3}`,`${URL4}`) # Can use same URL for each if using fewer than 4
      - traefik.http.routers.$ROUTERNAME.entrypoints=http, https
      - traefik.http.routers.$ROUTERNAME.tls=true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQLUSER}
      WORDPRESS_DB_PASSWORD: ${MYSQLPASSWORD}
      WORDPRESS_DB_NAME: ${MYSQLDATABASE}
networks:
  www:
    external: true 
  backend:
