version: '3.1'
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    volumes:
      - ${DOCKERROOT}/docker/overseerr/config:/config
    networks:
      - www
    ports:
      - 8009:5055
    restart: unless-stopped
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.overseerr.entrypoints=http, https
      - traefik.http.routers.overseerr.rule=Host(`${URL}`)
      - traefik.http.routers.overseerr.tls=true
networks:
  www:
    external: true
