version: '3.1'
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: www-overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    volumes:
      - /mnt/local/docker/overseerr/config:/config
    networks:
      - www
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.overseerr.entrypoints=web, websecure
      - traefik.http.routers.overseerr.rule=Host(`${URL}`)
      - traefik.http.routers.overseerr.tls=true
networks:
  www:
    external: true
