---
version: '3.1'
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=America/Chicago
    volumes:
      - $DOCKERDIR/sabnzbd/config:/config
      - $USERDIR/downloads/sabnzbd/sab_incomplete:/incomplete
      - $USERDIR/downloads/sabnzbd/sab_complete:/complete
    ports:
      - 8383:8080
      - 9191:9090
    restart: unless-stopped
