---
version: '3.1'
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - ${DOCKERDIR}/sabnzbd/config:/config
      - ${USERDIR}/downloads/sabnzbd/sab_incomplete:/incomplete
      - ${USERDIR}/downloads/sabnzbd/sab_complete:/complete
    ports:
      - ${PORTS1}
      - ${PORTS2}
    restart: always
