version: "3"
services:
  homer:
    image: ghcr.io/georgegedox/homergx:latest
    container_name: homergx
    volumes:
      - ${DOCKERROOT}/data:/www/assets
    environment:
      - UID=${UID}
      - GID=${GID}
    restart: unless-stopped
    ports:
      - ${PORT}:8080
