version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${UID}:${GID} 
    networks:
      - www 
    restart: always
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""  #leave blank to just use the URL in the router defined below.  Add /abc to have it as URL/abc if you choose
      #OPTIONAL
      ND_UIWELCOMEMESSAGE: "${MESSAGE}"
      #ND_GATRACKINGID: "${UATRACKERID{ #Send basic info to your own Google Analytics account. Must be in the format UA-XXXXXXXX
      ND_LASTFM_APIKEY: "${LASTFM_APIKEY}" #Last.fm ApiKey
      ND_LASTFM_SECRET: "${LASTFM_SECRET}" #Last.fm Shared Secret
      ND_SPOTIFY_ID: "${SPOTIFY_ID}" #Spotify Client ID. Required if you want Artist images
      ND_SPOTIFY_SECRET: "${SPOTIFY_SECRET}" #Spotify Client Secret. Required if you want Artist images
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.navidrome.rule=Host(`${URL}`)
      - traefik.http.routers.navidrome.entrypoints=web, websecure
      - traefik.http.routers.navidrome.tls=true
      - traefik.http.routers.navidrome.middlewares=authelia
    volumes:
      - "/mnt/local/docker/navidrome/config:/data"
      - "/mnt/music:/music:ro"
networks:
  www:
    external: true
