version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${UID}:${GID} 
    networks:
      - www 
    restart: always
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""  #leave blank to just use the URL in the router defined below.  Add /abc to have it as URL/abc if you choose
      #OPTIONAL
      ND_UIWELCOMEMESSAGE: "${MESSAGE}"
      #ND_GATRACKINGID: "${UATRACKERID{ #Send basic info to your own Google Analytics account. Must be in the format UA-XXXXXXXX
      ND_LASTFM_APIKEY: "${LASTFM_APIKEY}" #Last.fm ApiKey
      ND_LASTFM_SECRET: "${LASTFM_SECRET}" #Last.fm Shared Secret
      ND_SPOTIFY_ID: "${SPOTIFY_ID}" #Spotify Client ID. Required if you want Artist images
      ND_SPOTIFY_SECRET: "${SPOTIFY_SECRET}" #Spotify Client Secret. Required if you want Artist images
    ports:
      - 8008:4533
    labels:
      # Label to monitor container and restart if unhealthy
      - deunhealth.restart.on.unhealthy=true
      # Labels for Traefik
      - traefik.enable=true
      - traefik.docker.network=www
      - traefik.http.routers.navidrome.rule=Host(`${URL}`)
      - traefik.http.routers.navidrome.entrypoints=http, https
      - traefik.http.routers.navidrome.tls=true
      # Send to Authelia
      - traefik.http.routers.navidrome.middlewares=authelia@docker
      # OR Only allow certain IPs since it is internal - this is home IP
      #- traefik.http.middlewares.navidrome-whitelist.ipwhitelist.sourcerange=${ALLOW_IPS}
      ##Ignore the cloudflare IPs and show the IP user is coming from
      #- traefik.http.middlewares.navidrome-whitelist.ipwhitelist.ipstrategy.excludedips=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      #- traefik.http.routers.navidrome.middlewares=navidrome-whitelist@docker
    volumes:
      - "/mnt/local/docker/navidrome/config:/data"
      - "/mnt/music:/music:ro"
networks:
  www:
    external: true
